### ISSUE TITLE
Add a civic.json file

### ISSUE THREAD

**Issue by stvnrlly** [LeeMendelowitz/DCMetroMetrics#28]
A [civic.json file](http://codefordc.org/resources/specification.html) provides information about this project that's not included in the Github metadata. The full details of the format are [here](http://codefordc.org/resources/specification.html). Just put it in the root of your repo and we'll automatically display that info on the projects page.

Code for DC also has a tool to help put the file together [here](http://codefordc.org/resources/builder.html), and a validator to make sure everything's in the right place [here](http://codefordc.org/resources/validator.html).

(Also, since Code for DC is tracking this project, any issues tagged with `help wanted` will show up on http://codefordc.org/projects/helpwanted.html. If you are stuck on something, try that!)

**Comment by LeeMendelowitz** [comment]
Added civic.json in 5401acb

**Comment by tgmiller5** [comment]
Is it anything I can work on that is simple yet small

Sent from my HTC

----- Reply message -----
